### ISSUE TITLE
Context is ignored

### ISSUE THREAD

**Issue by ravinggenius** [gajus/roarr-middleware-serialize-error#1]
[Roarr's README](https://github.com/gajus/roarr#using-roarr-in-an-application) says to create a shared child logger that sets any common context. However the serialize error middleware appears to just ignore the context I pass in:

```js
import serializeError from '@roarr/middleware-serialize-error';
import roarr from 'roarr';

const rootLogger = roarr.child(serializeError({
	package: 'package-name'
}));

export default rootLogger;
```

Is there a way to work around this?

**Comment by gajus** [comment]
What are you trying to do?

To being with, `@roarr/middleware-serialize-error` doesn't have any parameters.

I guess you want:

```js
import serializeError from '@roarr/middleware-serialize-error';
import roarr from 'roarr';

const rootLogger = roarr
  .child({
    package: 'package-name'
  })
  .child(serializeError());

export default rootLogger;

```

**Comment by ravinggenius** [comment]
That's exactly what I was looking for, and I'm not sure why I didn't consider chaining `child` calls. Thanks!
