### ISSUE TITLE
Cannot correctly serialize errors due to roarr bug

### ISSUE THREAD

**Issue by Aankhen** [gajus/roarr-middleware-serialize-error#2]
[As noted already](https://github.com/gajus/roarr/commit/71eddbc25f4f6c1c547342161653fb30bbcd6bf3#commitcomment-32185252), the middleware cannot correctly serialize errors since [`roarr` first stringifies then parses the combined context](https://github.com/gajus/roarr/blob/5f856d969d5455727bbea770e1f5402ae04cd66c/src/factories/createLogger.js#L39-L42). The issue is gajus/roarr#18.

I thought I would open this issue for anyone else who’s wondering why this is happening.

**Comment by gajus** [comment]
Cannot produce in version `roarr@6.0.0`.
