### ISSUE TITLE
Is this package still the way to go?

### ISSUE THREAD

**Issue by benkroeger** [gajus/roarr-middleware-serialize-error#3]
I saw @gajus comment in [this](https://github.com/gajus/roarr/issues/58#issuecomment-1068323854) issue that he processes errors differently.

```js
import { Roarr as log } from 'roarr';
import { serializeError } from 'serialize-error';

try {
 doSomething();
} catch (err) {
  log.error({err: serializeError(err)}, "Something failed");
}
```

I'm just wondering if the middleware approach is not the way to go anymore?

**Comment by gajus** [comment]
This package does the same behind the scenes.

Personally, I like to explicitly serialize errors like in the example you shared.

Same outcome though.

**Comment by benkroeger** [comment]
ok, cool. thanks! Follow-up question though: can we update dependencies in  this package? It has a dependency on `roarr@2` which is doesn't allow deduping `roarr` when you have any other major version of roarr in your project's dependencies
